// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvzqtaGMoDeYvshm1XVAKQTZMvhX1dwrA',
    appId: '1:909371177297:web:33242002d0dc6dcc077b70',
    messagingSenderId: '909371177297',
    projectId: 'mobile-app-e9180',
    authDomain: 'mobile-app-e9180.firebaseapp.com',
    storageBucket: 'mobile-app-e9180.appspot.com',
    measurementId: 'G-Y5LZCBQ1P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SjG6D_LdN5mjVxyuH8wAcnGNmHdhdDo',
    appId: '1:909371177297:android:7a35acad22b78dd2077b70',
    messagingSenderId: '909371177297',
    projectId: 'mobile-app-e9180',
    storageBucket: 'mobile-app-e9180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW52o4qawxbAoGNA6l9qwFLASkYkucOjw',
    appId: '1:909371177297:ios:65cd002d24963978077b70',
    messagingSenderId: '909371177297',
    projectId: 'mobile-app-e9180',
    storageBucket: 'mobile-app-e9180.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW52o4qawxbAoGNA6l9qwFLASkYkucOjw',
    appId: '1:909371177297:ios:65cd002d24963978077b70',
    messagingSenderId: '909371177297',
    projectId: 'mobile-app-e9180',
    storageBucket: 'mobile-app-e9180.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvzqtaGMoDeYvshm1XVAKQTZMvhX1dwrA',
    appId: '1:909371177297:web:dba9e2a84281098b077b70',
    messagingSenderId: '909371177297',
    projectId: 'mobile-app-e9180',
    authDomain: 'mobile-app-e9180.firebaseapp.com',
    storageBucket: 'mobile-app-e9180.appspot.com',
    measurementId: 'G-J45K85ETL6',
  );
}
